global using Uxl.Back.Configs;
global using Uxl.Back.Settings;
global using Uxl.Back.Database;
global using Uxl.Back.Redirect;
global using Uxl.Back.ShortenUrl;
global using Uxl.Shared.ShortenUrl;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
